# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('postalcode', models.CharField(db_column='PostalCode', max_length=6, primary_key=True, serialize=False)),
                ('province', models.CharField(db_column='Province', max_length=25)),
                ('city', models.CharField(db_column='City', max_length=25)),
            ],
            options={
                'db_table': 'Addresses',
            },
        ),
    ]
