# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_auto_20170213_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=30)),
                ('AuthorizationNr', models.CharField(max_length=40)),
                ('CreationDate', models.DateField()),
                ('AuthorizationDate', models.DateField()),
                ('Street', models.CharField(max_length=10)),
                ('PostalCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PostalCode')),
            ],
            options={
                'db_table': 'Pharmacies',
            },
        ),
    ]
