# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170213_2034'),
        ('pharmacies', '0002_pharmacist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('MedicineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Medicine')),
                ('PharmacyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacies.Pharmacy')),
            ],
            options={
                'db_table': 'PharmaciesProducts',
            },
        ),
    ]
