# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170213_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('PostalCode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Province', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Addresses',
            },
        ),
    ]
