# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmploymentDate', models.DateField()),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('WholesaleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesales.Wholesale')),
            ],
            options={
                'db_table': 'Salers',
            },
        ),
    ]
