# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170213_2034'),
        ('wholesales', '0002_saler'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('MedicineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Medicine')),
                ('WholesaleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesales.Wholesale')),
            ],
            options={
                'db_table': 'WholesalesProducts',
            },
        ),
    ]
